export const cs = {
  dFlex: {display: "flex"},
  flexAuto: {flex: "auto"},
  flexColumn: {flexDirection: "column"},
  flexRow: {flexDirection: "row"},
  alignItemsCenter: {alignItems: "center"},
  justifyContentCenter: {justifyContent: "center"},
  justifyContentBetween: {justifyContent: "space-between"},
  justifyContentEnd: {justifyContent: "flex-end"},
  justifyContentStart: {justifyContent: "flex-start"},
  w25: {width: "25%"},
  w50: {width: "50%"},
  w75: {width: "75%"},
  w100: {width: "100%"},
  h100: {height: "100%"},
  gapSm: {gap: 14},
  gapMd: {gap: 24},
  gapLg: {gap: 36},
  p0: {padding: 0},
  p1: {padding: 8},
  p2: {padding: 16},
  p3: {padding: 24},
  p4: {padding: 32},
  p5: {padding: 40},
  m0: {margin: 0},
  m1: {margin: 8},
  m2: {margin: 16},
  m3: {margin: 24},
  m4: {margin: 32},
  m5: {margin: 40},
  mt1: {marginTop: 8},
  mt2: {marginTop: 16},
  mt3: {marginTop: 24},
  mt4: {marginTop: 32},
  mt5: {marginTop: 40},
  mb1: {marginBottom: 8},
  mb2: {marginBottom: 16},
  mb3: {marginBottom: 24},
  mb4: {marginBottom: 32},
  mb5: {marginBottom: 40},
  ml1: {marginLeft: 8},
  ml2: {marginLeft: 16},
  ml3: {marginLeft: 24},
  ml4: {marginLeft: 32},
  ml5: {marginLeft: 40},
  mr1: {marginRight: 8},
  mr2: {marginRight: 16},
  mr3: {marginRight: 24},
  mr4: {marginRight: 32},
  mr5: {marginRight: 40},
  cursorPointer: {cursor: "pointer"},
  textCenter: {textAlign: "center"},
  textLeft: {textAlign: "left"},
  textRight: {textAlign: "right"},
  textUppercase: {textTransform: "uppercase"},
  textCapitalize: {textTransform: "capitalize"},
  textBold: {fontWeight: "bold"},
  textItalic: {fontStyle: "italic"},
  textNowrap: {whiteSpace: "nowrap"},
  textTruncate: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
};

export const products = [
  {
    category: "Carts",
    quantity: 0,
    id: "10",
    name: "GHOST TRAIN HAZE CART 1G",
    thc: 84.39,
    cbd: 0.24,
    grams: 1,
    type: "Sativa",
    brand: "Torch",
    price: 90,
    image: require("../assets/images/vapocart1.jpg"),
    description:
      "Ghost Train Haze is a sativa cross between Ghost OG and Neville's Wreck. Unlike typical sativas, Ghost Train Haze grows dense buds blanketed in white, crystal-capped trichomes. With a sour citrus and floral aroma, Ghost Train Haze delivers a potent dose of THC to knock out pain, depression, and appetite loss, but patients prone to anxiety should steer clear of this heavy-hitter.",
  },
  {
    category: "Carts",
    quantity: 0,
    id: "20",
    name: "RUNTZ CART 1G",
    thc: 87.15,
    cbd: 0.27,
    grams: 1,
    type: "Hybrid",
    brand: "Torch",
    price: 50,
    image: require("../assets/images/vapocart2.jpg"),
    description:
      "Runtz is a rare sativa strain to find, so not much is known to-date about its THC and CBD averages. However, reviewers enjoy its sweet, fruity, and candy-like scent and taste as well as its spectrum of color. Runtz derives its name from the candy as it has a colorful appearance as well as a flavor profile that’s sugary-sweet.",
  },
  {
    category: "Carts",
    quantity: 0,
    id: "30",
    name: "STRAWBERRY BANANA GOO CART 1G",
    thc: 87.25,
    cbd: 0.3,
    grams: 1,
    type: "Indica",
    brand: "Torch",
    price: 40,
    image: require("../assets/images/vapocart3.jpg"),
    description:
      "Strawberry Banana is an indica developed by DNA Genetics in collaboration with Serious Seeds. A genetic cross of Crockett’s Banana Kush and the “Strawberry” phenotype of Bubble Gum, Strawberry Banana inherited a sweet, fruity flavor, hence the name. Known for its heavy resin production and high-THC content, Strawberry Banana produces happy, peaceful effects that sharpen creativity and sensory awareness.",
  },
  {
    category: "Carts",
    quantity: 0,
    id: "40",
    name: "OG SHARK CART 1G",
    thc: 87.64,
    cbd: 0.25,
    grams: 1,
    type: "Hybrid",
    brand: "Torch",
    price: 20,
    image: require("../assets/images/vapocart4.jpg"),
    description:
      "OG Shark, a rare strain found primarily in Canada, sets high standards with its impressive THC content and pungent, earthy aroma. Patients most commonly turn to this heavy-hitter for nausea, pain, and sleep disorders, as well as many other symptoms.",
  },
  {
    category: "Carts",
    quantity: 0,
    id: "50",
    name: "OG SHARK CART 1G",
    thc: 87.64,
    cbd: 0.25,
    grams: 1,
    type: "Hybrid",
    brand: "Torch",
    price: 20,
    image: require("../assets/images/vapocart5.jpg"),
    description:
      "OG Shark, a rare strain found primarily in Canada, sets high standards with its impressive THC content and pungent, earthy aroma. Patients most commonly turn to this heavy-hitter for nausea, pain, and sleep disorders, as well as many other symptoms.",
  },
  {
    category: "Carts",
    quantity: 0,
    id: "60",
    name: "OG SHARK CART 1G",
    thc: 87.64,
    cbd: 0.25,
    grams: 1,
    type: "Hybrid",
    brand: "Torch",
    price: 20,
    image: require("../assets/images/vapocart6.jpg"),
    description:
      "OG Shark, a rare strain found primarily in Canada, sets high standards with its impressive THC content and pungent, earthy aroma. Patients most commonly turn to this heavy-hitter for nausea, pain, and sleep disorders, as well as many other symptoms.",
  },
  {
    category: "Edibles",
    quantity: 0,
    id: "70",
    name: "GUMMYS JUICY PEACH 3500MG",
    thc: 70,
    cbd: 0.5,
    grams: 1,
    type: "Sativa",
    brand: "Torch",
    price: 20,
    image: require("../assets/images/gummy1.jpg"),
    description:
      "Juicy Peach Gummies by Torch are a delicious way to medicate. These tasty gummies come in a variety of flavors and are infused with 70% of THC per piece. Great for on-the-go or sharing with friends!",
  },
  {
    category: "Edibles",
    quantity: 0,
    id: "80",
    name: "GUMMYS JUICY PEACH 3500MG",
    thc: 70,
    cbd: 0.5,
    grams: 1,
    type: "Sativa",
    brand: "Torch",
    price: 20,
    image: require("../assets/images/gummy2.jpg"),
    description:
      "Juicy Peach Gummies by Torch are a delicious way to medicate. These tasty gummies come in a variety of flavors and are infused with 70% of THC per piece. Great for on-the-go or sharing with friends!",
  },
  {
    category: "Edibles",
    quantity: 0,
    id: "90",
    name: "GUMMYS JUICY PEACH 3500MG",
    thc: 70,
    cbd: 0.5,
    grams: 1,
    type: "Sativa",
    brand: "Torch",
    price: 20,
    image: require("../assets/images/gummy3.jpg"),
    description:
      "Juicy Peach Gummies by Torch are a delicious way to medicate. These tasty gummies come in a variety of flavors and are infused with 70% of THC per piece. Great for on-the-go or sharing with friends!",
  },
  {
    category: "Edibles",
    quantity: 0,
    id: "100",
    name: "GUMMYS JUICY PEACH 3500MG",
    thc: 70,
    cbd: 0.5,
    grams: 1,
    type: "Sativa",
    brand: "Torch",
    price: 20,
    image: require("../assets/images/gummy4.jpg"),
    description:
      "Juicy Peach Gummies by Torch are a delicious way to medicate. These tasty gummies come in a variety of flavors and are infused with 70% of THC per piece. Great for on-the-go or sharing with friends!",
  },
  {
    category: "Edibles",
    quantity: 0,
    id: "110",
    name: "GUMMYS JUICY PEACH 3500MG",
    thc: 70,
    cbd: 0.5,
    grams: 1,
    type: "Sativa",
    brand: "Torch",
    price: 20,
    image: require("../assets/images/gummy5.jpg"),
    description:
      "Juicy Peach Gummies by Torch are a delicious way to medicate. These tasty gummies come in a variety of flavors and are infused with 70% of THC per piece. Great for on-the-go or sharing with friends!",
  },
  {
    category: "Edibles",
    quantity: 0,
    id: "120",
    name: "GUMMYS JUICY PEACH 3500MG",
    thc: 70,
    cbd: 0.5,
    grams: 1,
    type: "Sativa",
    brand: "Torch",
    price: 20,
    image: require("../assets/images/gummy6.jpg"),
    description:
      "Juicy Peach Gummies by Torch are a delicious way to medicate. These tasty gummies come in a variety of flavors and are infused with 70% of THC per piece. Great for on-the-go or sharing with friends!",
  },
  {
    category: "Edibles",
    quantity: 0,
    id: "130",
    name: "GUMMYS JUICY PEACH 3500MG",
    thc: 70,
    cbd: 0.5,
    grams: 1,
    type: "Sativa",
    brand: "Torch",
    price: 20,
    image: require("../assets/images/gummy7.jpg"),
    description:
      "Juicy Peach Gummies by Torch are a delicious way to medicate. These tasty gummies come in a variety of flavors and are infused with 70% of THC per piece. Great for on-the-go or sharing with friends!",
  },
  {
    category: "Edibles",
    quantity: 0,
    id: "140",
    name: "GUMMYS JUICY PEACH 3500MG",
    thc: 70,
    cbd: 0.5,
    grams: 1,
    type: "Sativa",
    brand: "Torch",
    price: 20,
    image: require("../assets/images/gummy8.jpg"),
    description:
      "Juicy Peach Gummies by Torch are a delicious way to medicate. These tasty gummies come in a variety of flavors and are infused with 70% of THC per piece. Great for on-the-go or sharing with friends!",
  },
];