export const cs = {
  dFlex: {display: "flex"},
  flexAuto: {flex: "auto"},
  flexColumn: {flexDirection: "column"},
  flexRow: {flexDirection: "row"},
  alignItemsCenter: {alignItems: "center"},
  justifyContentCenter: {justifyContent: "center"},
  justifyContentBetween: {justifyContent: "space-between"},
  justifyContentEnd: {justifyContent: "flex-end"},
  justifyContentStart: {justifyContent: "flex-start"},
  w25: {width: "25%"},
  w50: {width: "50%"},
  w75: {width: "75%"},
  w100: {width: "100%"},
  h100: {height: "100%"},
  gapSm: {gap: 14},
  gapMd: {gap: 24},
  gapLg: {gap: 36},
  p0: {padding: 0},
  p1: {padding: 8},
  p2: {padding: 16},
  p3: {padding: 24},
  p4: {padding: 32},
  p5: {padding: 40},
  m0: {margin: 0},
  m1: {margin: 8},
  m2: {margin: 16},
  m3: {margin: 24},
  m4: {margin: 32},
  m5: {margin: 40},
  mt1: {marginTop: 8},
  mt2: {marginTop: 16},
  mt3: {marginTop: 24},
  mt4: {marginTop: 32},
  mt5: {marginTop: 40},
  mb1: {marginBottom: 8},
  mb2: {marginBottom: 16},
  mb3: {marginBottom: 24},
  mb4: {marginBottom: 32},
  mb5: {marginBottom: 40},
  ml1: {marginLeft: 8},
  ml2: {marginLeft: 16},
  ml3: {marginLeft: 24},
  ml4: {marginLeft: 32},
  ml5: {marginLeft: 40},
  mr1: {marginRight: 8},
  mr2: {marginRight: 16},
  mr3: {marginRight: 24},
  mr4: {marginRight: 32},
  mr5: {marginRight: 40},
  cursorPointer: {cursor: "pointer"},
  textCenter: {textAlign: "center"},
  textLeft: {textAlign: "left"},
  textRight: {textAlign: "right"},
  textUppercase: {textTransform: "uppercase"},
  textCapitalize: {textTransform: "capitalize"},
  textBold: {fontWeight: "bold"},
  textItalic: {fontStyle: "italic"},
  textNowrap: {whiteSpace: "nowrap"},
  textTruncate: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
};
