export const AppConstants = {
  MONDAY: "Monday",
  TUESDAY: "Tuesday",
  WEDNESDAY: "Wednesday",
  THURSDAY: "Thursday",
  FRIDAY: "Friday",
  WEEK: "Week",
  MONTH: "Month",
  STATUS_SCHEDULED: "Scheduled",
  STATUS_IN_PROGRESS: "In Progress",
  STATUS_DRAFT: "Draft",
  STATUS_DONE_SUCCESS: "Done (Success)",
  STATUS_DONE_FAILED: "Done (Failed)",
  INSPECTIONS: "Inspections",
  BUILDING: "Building",
  ADDRESS: "Address",
  DATE: "Date",
  TYPE: "Type",
  STATUS: "Status",
  MODEL: "Model",
  DEVICE: "Device",
  QUANTITY: "Quantity",
  LOCATION: "Location",
  ZONE: "Zone",
  CLIENT: "Client",
};